addReviewers: true
addAssignees: author

# Set this to the length of the reviewers list because the default was not including everyone
numberOfReviewers: 6

reviewers:
  - zubron
  - dsu-igeek
  - sseago
  - reasonerjt
  - ywk253100
